### ISSUE TITLE
AttributeError: 'AsyncConnection' object has no attribute 'cursor'.

### ISSUE THREAD

**Issue by leandroluk** [RazerM/sqlalchemy_aio#22]
hi first of all sorry for my english, google helped me.

I am trying to use `sqlalchemy` together with `sqlalchemy_aio` and panda but when trying to execute the code below:

    import sqlalchemy as sa
    import pandas as pd
    from sqlalchemy_aio import ASYNCIO_STRATEGY

    async def main():
        
        dsn = 'mysql://localhost:3306/test'
        engine = sa.create_engine(dsn, strategy=ASYNCIO_STRATEGY)
        conn = await engine.connect()
        
        sql = 'select * from test_table'
        
        df = pd.read_sql_query(sql, conn)

    
    if __name__ == '__main__':
        loop = asyncio.get_event_loop()
        loop.run_until_complete(main())
        loop.close()

you are experiencing an error:

    AttributeError: 'AsyncConnection' object has no attribute 'cursor'.

What do I need to do to be able to use the `sqlalchemy_aio` library with `panda`?

**Comment by RazerM** [comment]
I understand your English fine!

pandas does not work with our special async connection. In the example you show, there is no reason to use `sqlalchemy_aio`. I understand that it might just be an example. If you're trying to use pandas in a larger async application then you might want to do the following:

```python
await conn.run_in_thread(pd.read_sql_query, sql, conn.sync_connection)
```

You should be careful though, there are many pandas operations that will block the asyncio event loop. There are solutions like [`loop.run_in_executor`](https://docs.python.org/3.7/library/asyncio-eventloop.html#asyncio.loop.run_in_executor) you might want to look into.
