### ISSUE TITLE
AsyncEngine missing hide_parameters attribute

### ISSUE THREAD

**Issue by albertodonato** [RazerM/sqlalchemy_aio#36]
Since 1.3.8, SQLAlchemy `Engine`has a `hide_parameters` attribute (that can be passed to `create_engine`).

The `AsyncEngine` class doesn't provide a property to forward that attribute to the wrapped engine (see https://github.com/albertodonato/query-exporter/issues/62 for an example of the issue).

**Comment by RazerM** [comment]
Fixed in https://pypi.org/project/sqlalchemy-aio/0.17.0/
