### ISSUE TITLE
DeprecationWarning on python 3.9 and above: loop argument 

### ISSUE THREAD

**Issue by mattgodbolt** [RazerM/sqlalchemy_aio#40]
In Python3.9, using sqlalchemy_aio gives the following warning:
```
  .../lib/python3.9/site-packages/sqlalchemy_aio/asyncio.py:22: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
    self._request_queue = asyncio.Queue(1, loop=loop)
```

https://github.com/RazerM/sqlalchemy_aio/blob/a8f9c72fe03d50cc8155681dffa89852978086f7/sqlalchemy_aio/asyncio.py#L27

Seems the `loop` argument is going away entirely; which is likely to become more of a problem with Python 3.10 :)

**Comment by RazerM** [comment]
Fixed in https://pypi.org/project/sqlalchemy-aio/0.17.0/
